#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
AUTH_CONFIG="$PROJECT_DIR/content/auth-config.json"
UOTTAWA_TENANT_ID="d41fdab1-7e15-4cfd-b5fa-7200e54deb6b"

# write_auth_config_client_id VALUE updates just the "clientId" field in
# content/auth-config.json, leaving redirectUri and formatting intact.
write_auth_config_client_id() {
  local value="$1"
  python3 - "$AUTH_CONFIG" "$value" <<'PYEOF'
import json, sys
path, client_id = sys.argv[1], sys.argv[2]
with open(path) as f:
    data = json.load(f)
data["clientId"] = client_id
with open(path, "w") as f:
    json.dump(data, f, indent=2)
    f.write("\n")
PYEOF
  printf '  %s✓ wrote%s clientId → %s\n' "$GREEN" "$RESET" "$AUTH_CONFIG"
}

TOTAL_STAGES=4

banner "University of Ottawa sign-in setup (Microsoft Entra ID)"

# ── Stage 1: create the app registration ───────────────────────────────────
stage "Register the app in Microsoft Entra ID"
say "This creates a free app under YOUR OWN Microsoft account. You don't need"
say "any special access to University of Ottawa's systems — the site will"
say "later be restricted to their tenant by configuration, not by permission."
open_url "https://portal.azure.com"
step "Sign in (or create a free personal Microsoft account if you don't have one)."
step "In the search bar at the top, go to 'Microsoft Entra ID'."
step "In the left sidebar, click 'App registrations', then '+ New registration'."
step "Name: Recruiting Prep Hub (or anything you'll recognize)."
warn "Under 'Supported account types', you MUST pick:"
note "    'Accounts in any organizational directory (Any Microsoft Entra ID"
note "     tenant - Multitenant)'"
note "  NOT the single-tenant option (you don't administer uOttawa's tenant),"
note "  and NOT the 'personal Microsoft accounts only' option."
step "Under 'Redirect URI', set the platform dropdown to 'Single-page application (SPA)'"
step "and paste exactly: http://localhost:8123/login.html"
step "Click 'Register'."
pause "Done registering the app? Press Enter to continue."

# ── Stage 2: confirm settings + copy the client ID ─────────────────────────
stage "Copy the Application (client) ID"
say "On the app's Overview page (you should already be there after Register):"
step "Copy the 'Application (client) ID' — it's a GUID, e.g. 11111111-2222-..."
note "This value is NOT a secret. It's safe to put directly in client-side code."
say ""
say "Two quick checks while you're here, both should already be correct:"
step "Left sidebar → 'Authentication' → confirm your SPA redirect URI is listed"
step "under 'Single-page application', and that the 'Access tokens' / 'ID tokens'"
step "implicit-grant checkboxes are left UNCHECKED (this app uses the newer,"
step "more secure auth-code + PKCE flow, not implicit grant)."
step "Left sidebar → 'API permissions' → confirm 'User.Read' (Microsoft Graph,"
step "Delegated) is already listed. Nothing to add, no admin consent needed."
note "No client secret is required anywhere in this setup — it's a public"
note "client (browser SPA), not a confidential client."
say ""
ask CLIENT_ID "Paste the Application (client) ID here:"

# ── Stage 3: write it into the project ──────────────────────────────────────
stage "Save the client ID into the project"
say "Writing it into content/auth-config.json ..."
write_auth_config_client_id "$CLIENT_ID"
note "redirectUri in that file is left as http://localhost:8123/login.html for now."
note "Once you know your GitHub Pages URL, add a SECOND redirect URI in Azure"
note "(Authentication → Add URI) for https://<username>.github.io/<repo>/login.html,"
note "and update redirectUri in auth-config.json to match before you publish."

# ── Stage 4: verify locally ─────────────────────────────────────────────────
stage "Verify it works"
say "In a separate terminal, from the project folder, run:"
note "    cd \"$PROJECT_DIR\" && python3 -m http.server 8123"
step "Open http://localhost:8123/index.html in your browser."
step "Click 'Sign in with University of Ottawa Account'."
say ""
say "You should land on a real Microsoft sign-in page. Check the address bar —"
say "the URL should contain this tenant ID:"
note "    $UOTTAWA_TENANT_ID"
say "If it does, sign-in is correctly restricted to University of Ottawa,"
say "even though you're testing from your own Microsoft/Azure account."
note "You don't need an actual @uottawa.ca account to verify this step — just"
note "confirm the redirect happens and there's no 'invalid client' error."
say ""
confirm "Did the Microsoft sign-in page load with that tenant ID in the URL?" \
  && say "Setup verified." \
  || warn "If it failed, double-check the client ID in content/auth-config.json"

finish
